### PR TITLE
Fix checking if `navigator.geolocation` is available and how `buildMap` is called

### PR DESCRIPTION
**Pull request by alexclarkofficial**
Made a more robust check to see if the browser has `navigator.geolocation` and that the user allows it
Wrapped the call to `buildMap` in a function that passes position

### CODE REVIEW

**Comment by wifelette** [comment]
Heya—

There are a bunch of older additional commits packaged up here, unsure why. Do you need to rebase, perhaps? Let's definitely get it sorted before we merge this in.

Also, adding the reference link: https://github.com/emberjs/website/pull/1904

**Comment by alexclarkofficial** [comment]
Hey,

Yeah, I probably need to rebase. Sorry, I'm really new to open source. Also, I got a bit ahead of myself and the code doesn't do quite what I thought it did. I'll get this cleaned up and send it back over. Thanks for your patience!

**Comment by wifelette** [comment]
S'all good—most of the people working on this PR are super new, so we're all making lots of newbie mistakes :p We'll get it done though!

We'll keep an eye out for your updates.

**Comment by alexclarkofficial** [comment]
Got in over my head with this one. Ended up redoing the PR at sandraor/website#9.

**Pull request closed without merging**
