### PR TITLE
Add geocode rake task to geocode locations in meetups.yml using the geoc...

### PR DESCRIPTION
**Pull request by solsberg**
I've taken a swing at geocoding the locations in meetups.yml and then creating the markers for this geocoded data. 

The geocoding process is handled by a rake task: `rake geocode`
This uses the geocoder gem to calculate lon/lat coordinates for all location records in meetups.yml that don't currently have values for these keys. It rewrites the new data back to the same file.

I have then updated the script in meetups.html.erb to create markers for all these locations - via a helper in config.rb

I also added javascript to center the map at the user's current location using the geolocation API, given permission.

fyi: my first attempt at a pull request ;)

### CODE REVIEW

**Comment by solsberg** [comment]
I have rebased my branch so that it now builds upon the changes in https://github.com/sandraor/website/pull/1

**Comment by solsberg** [comment]
I have refactored my PR again so that now the geocoded locations are written to a separate json file (leaving the original meetups.yml unmodified). The json data is loaded at runtime and used to build the markers.

**Comment by wifelette** [comment]
I assume this keeps getting missed because it doesn't have a needed reference to https://github.com/emberjs/website/pull/1904. 

So first, there, now it does :stuck_out_tongue:.

Second, can this be rebased (again)? Might want to wait until @lzcabrera and @andrewbranch get their current conflict sorted though, so it's hopefully the _last_ needed rebase...

**Comment by wifelette** [comment]
I should add... if it's still needed. There's probably some overlap in the work, but hopefully much of both bits are still useful.

**Comment by solsberg** [comment]
it looks like the @lzcabrera PR already includes an alternative approach to generating the markers, the main differences being that my approach uses an underscore template to generate the infowindow html rather than a more imperative approach with javascript, and also I put the data in a separate json file rather than in a meta tag on the page. So if that one gets accepted then I guess the only question is whether you want to use my approach of calculating the lon/lat coordinates in a separate rake task rather than manually providing entering these values into the meetups.yml file

**Comment by wifelette** [comment]
The geocoder rake approach seems vastly superior—less manual data entry required :) Pretty please do separate this out and resubmit or edit this PR.  (@sandraor, correct me if you think otherwise)

I'm excited!

**Comment by solsberg** [comment]
OK. I'll try to take another look in the next day or 2, and probably create
a new branch and submit a new pull request.
Thanks

**Comment by solsberg** [comment]
This is replaced by https://github.com/sandraor/website/pull/10

**Pull request closed without merging**
